from pydantic import BaseModel
from datetime import datetime
from typing import Optional

# --- Post Schemas ---

# Base properties for a post, shared by other schemas
class PostBase(BaseModel):
    title: str
    content: str

# Schema for creating a new post. It inherits from PostBase.
class PostCreate(PostBase):
    pass

# Schema for updating a post. All fields are optional.
class PostUpdate(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None

# Schema for reading a post from the API (e.g., in a response).
# This includes properties that are generated by the database.
class Post(PostBase):
    id: int
    author_id: int
    time_created: datetime
    time_updated: Optional[datetime] = None

    class Config:
        # This allows the Pydantic model to be created from an ORM model
        from_attributes = True
